### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by lucacastelnuovo** [miladrahimi/phpcontainer#2]
Could you add php8 to composer.json

**Comment by miladrahimi** [comment]
Thanks for your suggestion. Here is the new release:
https://github.com/miladrahimi/phpcontainer/releases/tag/v5.2.4

**Comment by prod-broke-again** [comment]
> Thanks for your suggestion. Here is the new release: https://github.com/miladrahimi/phpcontainer/releases/tag/v5.2.4

php 8.1 support?

**Comment by miladrahimi** [comment]
It should work on 8.1, did you get any error?
